subscribers:

  camera_reading:
    topic: /summit_xl/front_rgbd_camera/rgb/image_raw
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image
    queue_size: 1
    latch: false

image_view:

  enable_opencv: false # Enable or disable the open cv view of the detection image including the bounding boxes.
  wait_key_delay: 1 # Wait key delay in ms of the open cv window.
  enable_console_output: true
